name: Container Ontology Regression tests
on: [push, pull_request, workflow_dispatch]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: build_python_environment
        shell: bash
        run: python3 -m pip install pytest docker requests
      - name: do_pytest
        shell: bash
        working-directory: ./container-ontology
        run: python -m pytest
      - name: save_server_logs
        if:  ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: server-log
          path: container-ontology/owl/owlery-conf/owlery.log

            
